{
    presets: "3", # Sets the presets file | '?' for asking | 'n' for sites.txt | '1' for http/s | '2' for socks4 | '3' for socks5

    removeWebsites: "y", # Removes not connectable websites | '?' for asking | 'y' or 'n'

    removeProxyless: "n", # Removes websites if no proxies are found | '?' for asking | 'y' or 'n'

    randomUseragent: "y", # Decides if random useragent is used | '?' for asking | 'y' for random useragent | 'n' will use the most common useragent

    threads: "40", # '?' for asking | '[Threadcount]'

    timeout: "10" # Sets timeout for the sites | '?' for asking | '[seconds]' | '10' is default
}